name = "Ene4302a"
uuid = "b92ae0ef-2d67-44cc-8a56-2d81bbaef28c"
version = "1.0.0-DEV"
authors = ["Vincent Le Chenadec <vincentlechenadec@gmail.com> and contributors"]

[deps]
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"

[weakdeps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
PlotsExt = "Plots"

[compat]
NLsolve = "4.5.1"
Plots = "1.41.5"
julia = "1.10.10"
