name = "Ene4302a"
uuid = "b92ae0ef-2d67-44cc-8a56-2d81bbaef28c"
authors = ["Vincent Le Chenadec <vincentlechenadec@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
